In [1]:
import pandas as pd
df=pd.read_csv("../data/raw/water_potability.csv")
(df.isnull().sum() / len(df)) * 100

ph                 14.987790
Hardness            0.000000
Solids              0.000000
Chloramines         0.000000
Sulfate            23.840049
Conductivity        0.000000
Organic_carbon      0.000000
Trihalomethanes     4.945055
Turbidity           0.000000
Potability          0.000000
dtype: float64

In [2]:
df_clean=df.copy()

In [3]:
print("Missing Values Before Cleaning")
print(df_clean.isnull().sum())

Missing Values Before Cleaning
ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [4]:
columns = ["ph", "Sulfate", "Trihalomethanes"]

for col in columns:
    median_value = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(median_value)

In [5]:
print("Missing Values After Cleaning")
print(df_clean.isnull().sum())

Missing Values After Cleaning
ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [6]:
comparison = pd.DataFrame({
    "Before": df.isnull().sum(),
    "After": df_clean.isnull().sum()
})

comparison

                 Before  After
ph                  491      0
Hardness              0      0
Solids                0      0
Chloramines           0      0
Sulfate             781      0
Conductivity          0      0
Organic_carbon        0      0
Trihalomethanes     162      0
Turbidity             0      0
Potability            0      0

In [7]:
print("Original Shape :", df.shape)
print("Clean Shape    :", df_clean.shape)

Original Shape : (3276, 10)
Clean Shape    : (3276, 10)

In [8]:
df_clean.to_csv("../data/processed/water_potability_clean.csv", index=False)

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [10]:
import pandas as pd

df = pd.read_csv("../data/processed/water_potability_clean.csv")

df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.036752,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,333.073546,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,333.073546,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [11]:
X = df.drop("Potability", axis=1)
y = df["Potability"]

In [12]:
from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Scale only the features
X_standard = scaler.fit_transform(X)

# Convert back to DataFrame
X_standard = pd.DataFrame(X_standard, columns=X.columns)

# Display first 5 rows
X_standard.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,-0.025474,0.259195,-0.139471,0.112415,0.965957,1.708954,-1.180651,1.305434,-1.286298
1,-2.284717,-2.036414,-0.385987,-0.307694,-0.014799,2.062575,0.270597,-0.639186,0.684218
2,0.697319,0.847665,-0.240047,1.360594,-0.014799,-0.094032,0.781117,0.000800,-1.167365
3,0.845393,0.547651,0.000493,0.592008,0.644130,-0.778830,1.255134,2.152154,0.848412
4,1.372982,-0.464429,-0.460249,-0.363698,-0.649522,-0.343939,-0.824357,-2.182297,0.138786

In [13]:
from sklearn.preprocessing import MinMaxScaler

# Create scaler
scaler = MinMaxScaler()

# Scale features
X_minmax = scaler.fit_transform(X)

# Convert back to DataFrame
X_minmax = pd.DataFrame(X_minmax, columns=X.columns)

# Display first 5 rows
X_minmax.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,0.502625,0.571139,0.336096,0.543891,0.680385,0.669439,0.313402,0.699753,0.286091
1,0.265434,0.297400,0.300611,0.491839,0.579704,0.719411,0.497319,0.450999,0.576793
2,0.578509,0.641311,0.321619,0.698543,0.579704,0.414652,0.562017,0.532866,0.303637
3,0.594055,0.605536,0.356244,0.603314,0.647347,0.317880,0.622089,0.808065,0.601015
4,0.649445,0.484851,0.289922,0.484900,0.514545,0.379337,0.358555,0.253606,0.496327

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
import pandas as pd

df = pd.read_csv("../data/processed/water_potability_clean.csv")

df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.036752,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,333.073546,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,333.073546,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [17]:
X = df.drop("Potability", axis=1)
y = df["Potability"]

print("X Shape :", X.shape)
print("y Shape :", y.shape)

X Shape : (3276, 9)
y Shape : (3276,)

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(2620, 9)
(656, 9)
(2620,)
(656,)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_standard = scaler.fit_transform(X_train)

X_test_standard = scaler.transform(X_test)

In [21]:
X_train_standard = pd.DataFrame(
    X_train_standard,
    columns=X.columns
)

X_test_standard = pd.DataFrame(
    X_test_standard,
    columns=X.columns
)

X_train_standard.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,-0.312812,0.202046,-0.554634,-0.666527,-0.601949,-0.199296,0.506221,-0.085006,-1.341104
1,-0.271043,-0.080066,1.368736,1.743813,0.304512,0.882586,-1.654207,0.018383,0.090829
2,-0.167550,0.283021,-0.423990,-0.248791,-0.985682,0.838486,-0.134860,0.274303,1.274183
3,-0.030325,-0.397879,-1.063086,1.681607,-0.376936,0.690172,-0.286851,-1.231655,-0.923584
4,-0.461061,-0.416413,-0.477227,0.223520,-0.028373,-0.340518,0.928554,-0.145027,0.788260

In [27]:
print(X_train_standard.mean())

ph                 2.671315e-16
Hardness           1.233958e-16
Solids             1.708557e-16
Chloramines        2.325536e-16
Sulfate           -6.183349e-16
Conductivity       8.678385e-17
Organic_carbon    -8.054626e-16
Trihalomethanes    5.396870e-16
Turbidity         -2.996755e-16
dtype: float64

In [26]:
print(X_train_standard.std())

ph                 1.000191
Hardness           1.000191
Solids             1.000191
Chloramines        1.000191
Sulfate            1.000191
Conductivity       1.000191
Organic_carbon     1.000191
Trihalomethanes    1.000191
Turbidity          1.000191
dtype: float64

In [28]:
import joblib

joblib.dump(scaler, "../models/standard_scaler.pkl")

['../models/standard_scaler.pkl']

In [29]:
import os

os.listdir("../models")

['random_forest.pkl', 'standard_scaler.pkl']

In [30]:
import joblib

scaler = joblib.load("../models/standard_scaler.pkl")

print(type(scaler))

<class 'sklearn.preprocessing._data.StandardScaler'>